### ISSUE TITLE
Add DBpedia classification example

### ISSUE THREAD

**Issue by ilblackdragon** [google/skflow#10]
DBPedia classification like in "[Character-level Convolutional Networks for Text Classification](http://arxiv.org/pdf/1509.01626v2.pdf)" is a good example to showcase:
 * Character level inputs
 * CNN for characters
 * show how much simpler than https://github.com/zhangxiangxiao/Crepe

**Comment by ilblackdragon** [comment]
Done. The models in examples are a lot simpler and work on word and character level RNN and CNN.

**Comment by marziehsaeidi** [comment]
Hi,  I am trying to run Text Classification examples but it seems datasets is not recognised under skflow:

module 'skflow' has no attribute 'datasets'

**Comment by terrytangyuan** [comment]
You need to install the most recent release of TensorFlow and check the [examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow) there. Please post issues to TensorFlow repo.

**Comment by zd123** [comment]
Hey, if you dont want to re-install the nightly build, you can manually download the same dataset.  I've documented ez steps here:  http://stackoverflow.com/questions/37206459/tensorflow-examples-all-fail-due-to-attributeerror-module-object-has-no-attri

**Comment by jeffheaton** [comment]
I think some compile errors have been introduced to this example from all the TF changes

**Comment by neuralminds** [comment]
thanks for these examples. just tried with Text Classification for character_rnn now how can i write a serving_input_fn for it ?
Thanks
