### ISSUE TITLE
DB pedia text classification shows " TypeError: data type not understood"

### ISSUE THREAD

**Issue by s4sarath** [google/skflow#11]
All the passed Parameter shape is correct . i have cross validated that .

**Comment by ilblackdragon** [comment]
Can you please show a stack trace? 
And also which version of scikit learn do you have? It seems like older versions had the different semantics of array checking.

**Comment by s4sarath** [comment]
Give me half an hour...

**Comment by s4sarath** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-10-27cd875193a5> in <module>()
----> 1 classifier.fit(X_train, y_array)

/Library/Python/2.7/site-packages/skflow/__init__.pyc in fit(self, X, y)
    111         """
    112         # Sets up data feeder.
--> 113         self._setup_data_feeder(X, y)
    114         if not self.continue_training or not self._initialized:
    115             # Sets up model and trainer.

/Library/Python/2.7/site-packages/skflow/__init__.pyc in _setup_data_feeder(self, X, y)
     69         else:
     70             self._data_feeder = data_feeder.DataFeeder(X, y,
---> 71                 self.n_classes, self.batch_size)
     72 
     73     def _setup_training(self):

/Library/Python/2.7/site-packages/skflow/data_feeder.pyc in __init__(self, X, y, n_classes, batch_size)
     60     def __init__(self, X, y, n_classes, batch_size):
     61         self.X = check_array(X, ensure_2d=False,
---> 62                              allow_nd=True, dtype=[np.float32, np.int64])
     63         self.y = check_array(y, ensure_2d=False, dtype=np.float32)
     64         self.n_classes = n_classes

/Library/Python/2.7/site-packages/sklearn/utils/validation.pyc in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features)
    342             else:
    343                 dtype = None
--> 344         array = np.array(array, dtype=dtype, order=order, copy=copy)
    345         # make sure we actually converted to numeric:
    346         if dtype_numeric and array.dtype.kind == "O":

TypeError: data type not understood

sklearn version =  0.16.1

**Comment by ilblackdragon** [comment]
It seems like the data type of X_train is not understood by check_array. 
Can you print the type(X_train) and X_train.dtype? It supposes to be a 2-dimensional numpy matrix of dtype.float32.
And you are running the same code as in text_classification.py or modified - if yes, can you show what you modified?

**Comment by s4sarath** [comment]
type(X_train) => numpy.ndarray
X_train.dtype => dtype('int64')

**Comment by s4sarath** [comment]
@ilblackdragon  - I have converted X_train as you mentioned by , X_train.astype('float32') . But still the same error . It is 2d array of size (560000, 10) .

**Comment by s4sarath** [comment]
@ilblackdragon - I am running the same code as in text_classififcation.py . As I am new to tensorflow , I thought if starting from the examples you have provided .

**Comment by ilblackdragon** [comment]
Ok, so I reproduced the issue with sklearn 0.16.1.
Quick fix for you to update your sklearn to 0.17. I'll in a meanwhile try to find what is the difference.

**Comment by s4sarath** [comment]
Ok I will do that , now . Thanks .

**Comment by s4sarath** [comment]
@ilblackdragon - Still no help . I ugraded scikit-learn to 0.17 . Still it is giving the same error .

**Comment by ylhsieh** [comment]
I have encountered this problem, and upgrading to 0.17 did solve the problem. So, @s4sarath could you try to remove scikit-learn and re-install 0.17. Maybe there are multiple installations of scikit in your system and python is not picking up the latest version.

**Comment by s4sarath** [comment]
I have uninstalled using pip and upgrade using pip . let me try once more .

**Comment by s4sarath** [comment]
Hi guys . it is working after updating sklearn to 0.17 . if anyone updating
, please make sure that you have removed all the previous version from
site-packages .

**Comment by ilblackdragon** [comment]
Hey guy, just FYI - I've fixed this issue and also started running tests with sklearn 0.16 (will add it for CI as well). Thanks for raising it!

**Comment by s4sarath** [comment]
Good thing man . thanks .
