### ISSUE TITLE
how to install scipy, scikit and skflow (using pip) with proper dependencies to python 2.7 and how to compile skflow examples using the bazel

### ISSUE THREAD

**Issue by vnkmr7620** [google/skflow#12]
very good tutorial. I tried installing tensoflow using the pip and i successfully installed and i tried to run the rnn examples but that folder will not be installed when we use pip. So i got suggestion to install bazel to compile and build the rnn examples.Obviously i installed the python and numpy inorder to run the tensorflow examples and i am able to compile and run the rnn examples successfully.
To follow your tutorial obviously i need to install scipy, scikit and and finally skflow. I am using python 2.7. Could you please tell us how to install scipy , scikit and skflow with proper dependencies (using pip) and finally after installation, how to run skflow examples using bazel (command for compiling and running skflow examples)

**Comment by ilblackdragon** [comment]
You should be able to install the TensorFlow and skflow without bazel.

The easiest way, is something like this (on Linux machine):
```bash
sudo apt-get install python-virtualenv # install python virtual environment
cd <some new folder>
virtualenv env # creates a new environment in this folder
activate env/bin/activate  # this activates virtual environment
pip install sklearn
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
pip install git+https://github.com/google/skflow.git
```

And then clone the whole repository locally to run examples:
```bash
git clone git+https://github.com/google/skflow.git
python skflow/examples/text_classification.py
```

For Mac,  you need to change how you install `virtualenv` and change TensorFlow path to Mac specific one.

Let me know if you have issues with this.
