### ISSUE TITLE
 Error raised when importing skflow with tensorflow 0.6.0 installed

### ISSUE THREAD

**Issue by jharaldson** [google/skflow#27]
Tensorflow 0.6.0 is not officially released, but importing skflow with tensorflow 0.6.0 installed raises an error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cb8af396def9> in <module>()
----> 1 import skflow

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skflow/__init__.py in <module>()
     27 
     28 from skflow.trainer import TensorFlowTrainer
---> 29 from skflow import models, data_feeder
     30 from skflow import preprocessing
     31 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skflow/models.py in <module>()
     16 import tensorflow as tf
     17 
---> 18 from skflow.ops import mean_squared_error_regressor, softmax_classifier, dnn
     19 
     20 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skflow/ops/__init__.py in <module>()
     16 
     17 from skflow.ops.conv_ops import *
---> 18 from skflow.ops.dnn_ops import *
     19 from skflow.ops.embeddings_ops import *
     20 from skflow.ops.losses_ops import *

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skflow/ops/dnn_ops.py in <module>()
     17 
     18 import tensorflow as tf
---> 19 from tensorflow.models.rnn import linear
     20 
     21 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/models/rnn/linear.py in <module>()
     24 import tensorflow as tf
     25 
---> 26 linear = tf.nn.linear

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'linear'

**Comment by lukaszkaiser** [comment]
In 0.6 the function linear is in rnn_cell and you can call it from there.
