### ISSUE TITLE
OSX Multi threading

### ISSUE THREAD

**Issue by ivallesp** [google/skflow#28]
Is there any way of determining the number of cores in OSX? I think it calculates it automatically but in my case, I see in the system Monitor a Python process with a %CPU of 150% while other algorithms like XGBOOST mark over 300%. Could I set it manually?

Note that I'm executing the iris_custom_model algorithm with a larger dataset

Thank you

**Comment by terrytangyuan** [comment]
Should be fixed by #31 so that you can pass a `num_cores` to set it manually.

**Comment by ivallesp** [comment]
Ok, I'm going to try it. Thank you
