### ISSUE TITLE
Model Persistence

### ISSUE THREAD

**Issue by ivallesp** [google/skflow#37]
Is there any way of storing a model? I'm trying to pickle it with pickle and dill but it does not work...

Thank you

**Comment by ilblackdragon** [comment]
@ivallesp yeah, just pickling doesn't work you need to use tf.Saver. I have #23 open exactly for that.

**Comment by ilblackdragon** [comment]
Fixed in recent commit #afb324d - use `save` and `restore` operations, for example see main readme. I'll also add an example into examples folder.
