### ISSUE TITLE
missing import 

### ISSUE THREAD

**Issue by pakdaman** [google/skflow#39]
in your example for multioutput regression, it seems that you should add the following import command, so the code will work properly

import skflow.ops

MP

**Comment by ilblackdragon** [comment]
Is it not running for you?
The ops should be imported by transitivity when `import skflow` is done.

**Comment by pakdaman** [comment]
I believe you are right. The code is running fine when i call python in the
eclipse. But, when i use iphython it raises an error. When i added the
import then it is ok. It might be a problem with my ipython configuration,
though.
