### ISSUE TITLE
ImportError: cannot import name NotFittedError

### ISSUE THREAD

**Issue by mrry** [google/skflow#47]
The [import](https://github.com/google/skflow/blob/5dbcc5afdb94675ab019ea08658c9a16b8db1162/skflow/estimators/base.py#L25) of `sklearn.utils.validation.NotFittedError` in `skflow/estimators/base.py` is no longer correct with the latest version if scikit-learn. In particular, [this commit](https://github.com/scikit-learn/scikit-learn/commit/e3afc0e8c9de522324a2f0cf0f7a17fee5147195) to scikit-learn moves `NotFittedError` to [`sklearn.exceptions.NotFittedError`](https://github.com/scikit-learn/scikit-learn/blob/6ff0bbe6f11e2398d06a3c91951f6b45677ae94c/sklearn/exceptions.py#L17).

Which versions of scikit-learn is skflow expected to support? (I would send a PR, but am not sure how you want to deal with backwards compatibility here.)

(Source: [this StackOverflow question](http://stackoverflow.com/questions/34418556/cannot-import-name-notfittederror-on-ubuntu).)

**Comment by ilblackdragon** [comment]
I think we would want to support 0.16, 0.17 and latest. I'll make sure CI has all of them in coming days. Your contributions are welcome, I'll though send a quick fix for this one.

**Comment by viksit** [comment]
A simple pip install and running the neural_translation.py example gives me the same error. Thoughts?

**Comment by terrytangyuan** [comment]
Try this `pip install git+git://github.com/tensorflow/skflow.git`. It should tell you to update some dependencies.

**Comment by terrytangyuan** [comment]
@ilblackdragon @mrry I suggest we create a `compat.py` file to deal with compatibility. We put a bunch of `try catch` and then import `NotFittedError` via `from compat import NotFittedError`. What do you think?
