### ISSUE TITLE
Plotting neural network built by skflow

### ISSUE THREAD

**Issue by vinhqdang** [google/skflow#58]
Hi,

Sorry I asked too much.

I think plotting is always a nice feature. Is it possible right now for skflow (or can we do that through tensorflow directly)?

**Comment by terrytangyuan** [comment]
We have just added this https://github.com/google/skflow#summaries
Is this what you want?

**Comment by vinhqdang** [comment]
Wow, it's great.

**Comment by ilblackdragon** [comment]
No worries about questions, they are always welcome! Some of them may be more suitable for chat here  - https://gitter.im/google/skflow

**Comment by vinhqdang** [comment]
Hi,

Today I tried to add *logdir* parameter to ``fit`` function, and I have a ``.local`` file of 45MB.

However, when I opened TensorBoard, it reported that there is no image, graph, or anything else.

I train the model continuously

```python
while True:
    classifier.fit(X_train, Y_train, logdir="./logdir/enwiki_classification_rnn_text")
```

and press ``Ctrl - C`` to stop. Maybe it is a problem?

**Comment by ilblackdragon** [comment]
How are you running tensorboard? 
It should be something like this: `tensorboard --logdir="logdir/my_model"`
And can you list the `logdir/my_model/<date>/` folder, it should have event files?

**Comment by vinhqdang** [comment]
Hi, I ran ``tensorboard`` command already. In my case, it used the port ``6006``

Well, in the directory ``logdir/my_model/date``, there is only 1 file with extension ``.local``

**Comment by ilblackdragon** [comment]
Something like this is correct: `logdir/my_model/2015-12-30_10-39-11/events.out.tfevents.1451500751.local`
What do you see in the tensorboard? 
Do you see something like `2015-12-30_10-39-11` in the list of runs?
Also which classifier are you running?

**Comment by vinhqdang** [comment]
Yeah, I saw the ``date`` in the list of runs, with four tabs: Events, Histogram, Graph, etc.

But when I clicked to each tab, it said that there is no Event with tags ...

I am following the example text_classifity with rnn of skflow

**Comment by ilblackdragon** [comment]
Can you send me your .local file? (my username at gmail.com)

**Comment by vinhqdang** [comment]
well, I ran it again and now I can view the graph. Maybe something wrong with previous run.

Thanks for your help
