### ISSUE TITLE
Early stopping , epoch and unsupervised learning.

### ISSUE THREAD

**Issue by saj1919** [google/skflow#61]
Hi, this is not an issue but wanted to get clear on some points or may be dumb questions.
I couldn't see parameters for early stopping and epoch (maybe missed it) But I saw steps. Is that equivalent to epoch or iterations.

Also, is unsupervised learning supported like in clustering , word2vec, self-taught type feature learning. Or there are future plans.

**Comment by terrytangyuan** [comment]
@saj1919 FYI, I am working on a PR for early stopping. It's a nice feature to have.
