### ISSUE TITLE
Error while using *early_stopping*

### ISSUE THREAD

**Issue by vinhqdang** [google/skflow#69]
Hello

Today I tried to use *early_stopping* feature (as [here](https://github.com/google/skflow/blob/master/examples/iris_early_stopping.py)), and I found that my current skflow cannot find the keyword ``early_stopping_rounds``.

I tried to reinstall skflow but it cannot upgrade because the version are the same (0.0.1). I have to first uninstall skflow then install it again.

So I think it would be good to update the version of skflow to update easier.

**Comment by terrytangyuan** [comment]
That's only minor addition so it doesn't make sense to make a new version out of it. You'll have to uninstall it first.

**Comment by vinhqdang** [comment]
Well, I have a different idea, but anyway ...

Thanks for your comment

**Comment by terrytangyuan** [comment]
Thanks for trying the new feature :-) We are developing fast so it's hard to do what you suggested. We'll do it soon though once the project is more stable.

**Comment by vinhqdang** [comment]
Yeah, at least I think it is good to mention it somewhere for other users to know how to get the new features :-P
